FROM python:3

WORKDIR /usr/src/app

COPY requirements/. requirements/
COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements/dev.txt

COPY . .

CMD [ "pytest", "--pep8", "--cov=telegram_bot", "--flakes" ]